import { AppError } from '../../shared/errors.js';
import type { MembershipRole, TenantContext } from '../../shared/tenant-context.js';

export const permissionActions = [
  'auth.csrf.issue',
  'auth.me',
  'auth.password.change',
  'auth.session.revoke_self',
  'company.read',
  'company.profile.update',
  'companies.read_current',
  'companies.create',
  'company.update',
  'members.read',
  'members.manage',
  'invitations.read',
  'invitations.manage',
  'invitations.accept_self',
  'members.role.change',
  'members.remove',
  'audit_logs.read',
  'frameworks.manage',
  'frameworks.read',
  'frameworks.enable',
  'controls.manage_applicability',
  'controls.read',
  'controls.manage',
  'dashboard.read',
  'evidence.upload',
  'evidence.read',
  'evidence.review',
  'evidence.manage',
  'mapping.create',
  'mapping.read',
  'mapping.review',
  'tasks.create',
  'tasks.update_assigned',
  'tasks.read',
  'tasks.manage',
  'tasks.review',
  'tasks.read_assigned',
  'tasks.read_all',
  'tasks.submit_assigned',
  'reports.generate',
  'reports.read',
  'reports.read_selected',
  'ai.run',
  'ai.read',
  'notifications.read',
  'comments.update',
  'comments.read',
  'comments.delete',
  'comments.create',
  'jobs.manage',
  'auditor_grants.manage',
  'auditor_grants.read',
  'deletion_requests.manage',
  'retention.read',
  'retention.manage',
] as const;

export type PermissionAction = (typeof permissionActions)[number];

type RolePermissionSeed = readonly PermissionAction[];

const ownerAdminSeed: RolePermissionSeed = [
  'auth.csrf.issue',
  'auth.me',
  'auth.password.change',
  'auth.session.revoke_self',
  'companies.create',
  'companies.read_current',
  'company.profile.update',
  'members.remove',
  'members.role.change',
  'frameworks.read',
  'controls.read',
  'evidence.manage',
  'mapping.read',
  'tasks.read',
  'tasks.update_assigned',
  'comments.create',
  'comments.delete',
  'comments.read',
  'comments.update',
  'invitations.accept_self',
  'invitations.manage',
  'invitations.read',
  'company.read',
  'company.update',
  'members.read',
  'members.manage',
  'audit_logs.read',
  'frameworks.manage',
  'frameworks.enable',
  'controls.manage_applicability',
  'controls.manage',
  'dashboard.read',
  'evidence.upload',
  'evidence.read',
  'evidence.review',
  'mapping.create',
  'mapping.review',
  'tasks.create',
  'tasks.manage',
  'tasks.review',
  'tasks.read_assigned',
  'tasks.read_all',
  'tasks.submit_assigned',
  'reports.generate',
  'reports.read',
  'reports.read_selected',
  'ai.run',
  'ai.read',
  'notifications.read',
  'jobs.manage',
  'auditor_grants.manage',
  'auditor_grants.read',
  'deletion_requests.manage',
  'retention.read',
  'retention.manage',
];

const complianceManagerSeed: RolePermissionSeed = [
  'auth.csrf.issue',
  'auth.me',
  'auth.password.change',
  'auth.session.revoke_self',
  'companies.read_current',
  'frameworks.read',
  'controls.read',
  'evidence.manage',
  'mapping.read',
  'tasks.read',
  'tasks.update_assigned',
  'comments.create',
  'comments.delete',
  'comments.read',
  'comments.update',
  'invitations.read',
  'company.read',
  'audit_logs.read',
  'frameworks.manage',
  'frameworks.enable',
  'controls.manage_applicability',
  'controls.manage',
  'dashboard.read',
  'evidence.upload',
  'evidence.read',
  'evidence.review',
  'mapping.create',
  'mapping.review',
  'tasks.create',
  'tasks.manage',
  'tasks.review',
  'tasks.read_assigned',
  'tasks.read_all',
  'tasks.submit_assigned',
  'reports.generate',
  'reports.read',
  'reports.read_selected',
  'ai.run',
  'ai.read',
  'notifications.read',
  'jobs.manage',
  'auditor_grants.manage',
  'auditor_grants.read',
  'retention.read',
];

const memberSeed: RolePermissionSeed = [
  'auth.csrf.issue',
  'auth.me',
  'auth.password.change',
  'auth.session.revoke_self',
  'companies.read_current',
  'controls.read',
  'tasks.read',
  'tasks.update_assigned',
  'comments.create',
  'comments.delete',
  'comments.read',
  'comments.update',
  'invitations.accept_self',
  'company.read',
  'evidence.upload',
  'evidence.read',
  'tasks.read_assigned',
  'tasks.submit_assigned',
  'notifications.read',
];

const auditorSeed: RolePermissionSeed = [
  'auth.csrf.issue',
  'auth.me',
  'auth.password.change',
  'auth.session.revoke_self',
  'companies.read_current',
  'controls.read',
  'comments.read',
  'invitations.accept_self',
  'company.read',
  'evidence.read',
  'reports.read',
  'reports.read_selected',
  'notifications.read',
  'auditor_grants.read',
];

const rolePermissions: Record<MembershipRole, ReadonlySet<PermissionAction>> = {
  OWNER: new Set(ownerAdminSeed),
  ADMIN: new Set(ownerAdminSeed),
  COMPLIANCE_MANAGER: new Set(complianceManagerSeed),
  MEMBER: new Set(memberSeed),
  AUDITOR: new Set(auditorSeed),
};

export function hasPermission(role: MembershipRole, action: PermissionAction): boolean {
  return rolePermissions[role].has(action);
}

export function requirePermission(tenant: TenantContext, action: PermissionAction): void {
  if (!hasPermission(tenant.role, action)) {
    throw new AppError({
      statusCode: 403,
      code: 'PERMISSION_DENIED',
      message: 'You do not have permission to perform this action.',
      details: [{ field: 'permission', reason: action }],
    });
  }
}

export function listPermissionsForRole(role: MembershipRole): PermissionAction[] {
  return [...rolePermissions[role]].sort();
}

export function isAuditorTenant(tenant: TenantContext): boolean {
  return tenant.role === 'AUDITOR';
}
